version: '3.8'

services:

  solr:
    image: solr
    profiles: ["prod"]
    volumes:
      - ./solr/data:/var/solr/
      - ./solr/configset:/owdex_configset:ro
      - ./solr/entrypoint.sh:/entrypoint.sh
    entrypoint:
    - /entrypoint.sh
  
  solr-dev:
    profiles: ["dev"]
    container_name: solr
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./solr/data:/var/solr/
      - ./solr/configset:/owdex_configset:ro
      - ./solr/entrypoint.sh:/entrypoint.sh
    entrypoint:
    - /entrypoint.sh

  mongo:
    profiles: ["prod"]
    image: mongo
  
  mongo-dev:
    container_name: mongo
    profiles: ["dev"]
    ports:
      - "27017:27017"
    image: mongo
  
  mongo-express:
    image: mongo-express
    profiles: ["dev"]
    restart: always
    ports:
      - "8081:8081"

  frontend:
    profiles: ["prod"]
    build: ./src
    ports:
      - "80:80"
