version: '3'

services:

  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./data:/var/solr/
      - ./solr_configset:/owdex_configset:ro
      - ./solr_configset_users:/owdex_configset_users:ro
      - ./solr_entrypoint.sh:/entrypoint.sh
    entrypoint:
    - /entrypoint.sh

  frontend:
    build: ./src
    ports:
      - "80:80"
    depends_on:
      - solr
